# 📘 TensorFlow Basics

TensorFlow is a powerful open-source library developed by Google for deep learning and numerical computation. It uses dataflow graphs and automatic differentiation to perform optimized computations.

Let's get started by learning how to use Tensors, which are the fundamental building blocks of TensorFlow.


In [25]:
# Installing and importing tensorflow :

!pip install tensorflow -q
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.21.0


## 📦 Tensors

Tensors are multi-dimensional arrays (like NumPy arrays). TensorFlow supports scalar (0D), vector (1D), matrix (2D), and higher dimensional tensors.

Let's see how to create and inspect them.

In [26]:
# scalar

scalar = tf.constant(7)
print("Scalar : ", scalar) 

vector = tf.constant([1.0, 2.0, 3.0])
print("Vector : ", vector)

matrix = tf.constant([[1,2], [3,4]])
print("Matrix : \n", matrix)

print('\nShape of matrix is : ', matrix.shape)
print('Data type of matrix is : ', matrix.dtype)

Scalar :  tf.Tensor(7, shape=(), dtype=int32)
Vector :  tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Matrix : 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Shape of matrix is :  (2, 2)
Data type of matrix is :  <dtype: 'int32'>


## ➕ Tensor Operations

TensorFlow supports element-wise operations like addition, multiplication, matrix multiplication, etc.

In [27]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[5,6], [7,8]])

# Addition : 
print(f"\nAddition : \n {tf.add(a,b)}")

# Multiplication (element-wise)
print("Element-wise Multiplication :\n", tf.multiply(a,b))

# Matrix Multiplication
print("Matrix Multiplication : \n", tf.matmul(a,b))


Addition : 
 [[ 6  8]
 [10 12]]
Element-wise Multiplication :
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication : 
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# 🏗️ Building a Neural Network with TensorFlow (Keras)

We'll use `tf.keras`, a high-level API for building and training models. Let's train a simple neural network to classify digits using the MNIST dataset.


In [29]:
# Load the dataset and normalize

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize to [0,1]
x_train, x_test = x_train / 255.0 , x_test / 255.0

In [36]:
print(x_train.shape)

(60000, 28, 28)


# Defining a model 

In [41]:
# Define a model  :

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),   #Input Layer
    tf.keras.layers.Dense(128, activation="relu"),   #Hidden Layer
    tf.keras.layers.Dense(10, activation="softmax")   #Output layer
])

# Compiling and Training a model : 

In [43]:
# Compiling the model : 
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# Training the model : 
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9244 - loss: 0.2645
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9659 - loss: 0.1160
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9761 - loss: 0.0804
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9818 - loss: 0.0596
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9864 - loss: 0.0461


## Evaluate the model : 


In [44]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Accuracy : ", test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9768 - loss: 0.0772
Test Accuracy :  0.9768000245094299


# Introduction to PyTorch
## 🔥 PyTorch Basics

PyTorch is a popular open-source deep learning library developed by Facebook AI. It provides flexibility and speed through dynamic computation graphs and strong GPU support.

In this section, we'll start by exploring how PyTorch handles tensors and automatic differentiation.


In [45]:
# Installing pytorch : 

# If you're in a notebook or Colab
!pip install torch -q
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.13.0+cpu


## 📦 Tensors in PyTorch

Tensors are multidimensional arrays, just like in NumPy. They're the building blocks of PyTorch and support operations like addition, multiplication, reshaping, etc.

In [53]:
# Scalar
scalar = torch.tensor(5)
print("Scalar : \n", scalar)

vector = torch.tensor([1.0,2.0,3.0])
print("Vector : \n", vector)

matrix = torch.tensor([[1,2], [3,4]])
print("Matrix : \n", matrix)

print('\nShape : ', matrix.shape)
print('\nType : ', matrix.dtype)

Scalar : 
 tensor(5)
Vector : 
 tensor([1., 2., 3.])
Matrix : 
 tensor([[1, 2],
        [3, 4]])

Shape :  torch.Size([2, 2])

Type :  torch.int64


## ➕ Tensor Operations

PyTorch supports common element-wise operations as well as matrix multiplication, reshaping, and broadcasting.

In [59]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
b = torch.tensor([[5,6],[7,8]], dtype=torch.float32)

In [61]:
print(a.dtype)
print(b.dtype)

torch.float32
torch.float32


In [62]:
# Addition
print("Addition:\n", a + b)

# Element-wise multiplication
print("Element-wise Multiplication:\n", a * b)

# Matrix multiplication
print("Matrix Multiplication:\n", torch.matmul(a, b))

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


# 🏗️ Building a Neural Network with PyTorch

Now let's build a simple neural network to classify digits from the MNIST dataset using `torch.nn` and `torch.optim`.

In [66]:
pip install torch torchvision

   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.2 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.2 MB 1.5 MB/s eta 0:00:03
   ----- ---------------------------------- 0.5/4.2 MB 1.5 MB/s eta 0:00:03
   ----- ---------------------------------- 0.5/4.2 MB 1.5 MB/s eta 0:00:03
   ------- -------------------------------- 0.8/4.2 MB 574.8 kB/s eta 0:00:06
   ---------- ----------------------------- 1.0/4.2 MB 800.6 kB/s eta 0:00:04
   --------------- ------------------------ 1.6/4.2 MB 1.0 MB/s eta 0:00:03
   -------------------- ------------------- 2.1/4.2 MB 1.2 MB/s eta 0:00:02
   ---------------------- ----------------- 2.4/4.2 MB 1.2 MB/s eta 0:00:02
   ---------------------- ----------------- 2.4/4.2 MB 1.2 MB/s eta 0:00:02
   --------------------------- -----

In [68]:
# Load and normalize the MNIST  dataset

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [70]:
# Transform :  Normalize the data from [0,1]
transform = transforms.ToTensor()

In [73]:
train_data = datasets.MNIST(root="data", train=True, download=True, transform=transform)
test_data = datasets.MNIST(root="data", train=False, download=True, transform=transform)

100%|██████████████████████████████████████████████████████████████████████████████| 9.91M/9.91M [00:36<00:00, 271kB/s]
100%|██████████████████████████████████████████████████████████████████████████████| 28.9k/28.9k [00:00<00:00, 128kB/s]
100%|██████████████████████████████████████████████████████████████████████████████| 1.65M/1.65M [00:07<00:00, 233kB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 4.54k/4.54k [00:00<00:00, 2.59MB/s]


In [81]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [82]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [83]:
train_loader = DataLoader(train_data,batch_size=64,shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)

## Defining Neural Network : 

In [89]:
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module) :
    def __init__(self) : 
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(28*28,128)
        self.fc2 = nn.Linear(128,10)

    def forward(self,x) : 
        x = x.view(x.shape[0],-1) #Flatten
        x = F.relu(self.fc1(x))
        return F.log_softmax(self.fc2(x), dim=1)

model = SimpleNN()

## Define Loss and Optimizer

In [90]:
import torch.optim as optim

In [91]:
criterion = nn.NLLLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [93]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

## Train the model

In [94]:
epochs = 3
for epoch in range(epochs) :
    for images, labels in train_loader : 
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output,labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}, Loss : {loss.item():.4f}")

Epoch 1, Loss : 0.1122
Epoch 2, Loss : 0.0562
Epoch 3, Loss : 0.0493


## Evaluate the model

In [96]:
correct = 0
total = 0

with torch.no_grad() : 
    for images, labels in test_loader : 
        output = model(images)
        _, predicted = torch.max(output,1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy : {correct / total * 100:.2f}%")

Test Accuracy : 96.86%


# PyTorch vs TensorFlow: Quick Comparison

| Feature                | PyTorch                               | TensorFlow                           |
|------------------------|----------------------------------------|--------------------------------------|
| Execution Mode         | Eager (Dynamic)                        | Eager (Static with option for Graph) |
| High-Level API         | `torch.nn`, `torch.optim`              | `tf.keras`                           |
| Dataset Loader         | `DataLoader`                           | `tf.data.Dataset`                    |
| Training Loop Style    | Mostly manual                          | `model.fit()` or manual              |
| Model Saving           | `torch.save()`                         | `model.save()` or `SavedModel`       |
| Visualization Tool     | TensorBoard (via `torch.utils.tensorboard`) | TensorBoard                    |
| Autograd Support       | Built-in via `autograd`                | `tf.GradientTape()`                  |

Both libraries are capable of building state-of-the-art models. Your choice depends on project needs and comfort with syntax.


## Exercise

## Creating a Custom Model in Tensorflow

# Building the Model

In [97]:
# Custom architecture: Flatten -> Dense(256, ReLU) -> Dropout(0.3) -> Dense(128, Tanh) -> Dense(10, Softmax)
custom_tf_model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(128, activation='tanh'),
    tf.keras.layers.Dense(10, activation='softmax')
])

C:\Users\hi\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


# compile and Train

In [98]:
custom_tf_model.compile(optimizer='adam',
                         loss='sparse_categorical_crossentropy',
                         metrics=['accuracy'])

custom_tf_model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 7ms/step - accuracy: 0.9271 - loss: 0.2402
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9619 - loss: 0.1198
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9707 - loss: 0.0932
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9743 - loss: 0.0793
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9776 - loss: 0.0695


## Evaluate the Model : 

In [100]:
tf_custom_loss, tf_custom_acc = custom_tf_model.evaluate(x_test, y_test)
print("\nTensorFlow Custom Model Test Accuracy:", tf_custom_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9797 - loss: 0.0669

TensorFlow Custom Model Test Accuracy: 0.9797000288963318


## PyTorch Custom Model

## Building the Model

In [101]:
class CustomNN(nn.Module):
    def __init__(self):
        super(CustomNN, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 256)
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(x.shape[0], -1)          # Flatten
        x = F.relu(self.fc1(x))             # Dense 1 + ReLU
        x = self.dropout(x)                 # Dropout 0.3
        x = torch.tanh(self.fc2(x))         # Dense 2 + Tanh
        return F.log_softmax(self.fc3(x), dim=1)  # Output + LogSoftmax

custom_torch_model = CustomNN()

## Loss and optimizer 

In [102]:
custom_criterion = nn.NLLLoss()
custom_optimizer = optim.Adam(custom_torch_model.parameters(), lr=0.001)

## Training 

In [ ]:
epochs = 5
for epoch in range(epochs):
    for images, labels in train_loader:
        custom_optimizer.zero_grad()
        output = custom_torch_model(images)
        loss = custom_criterion(output, labels)
        loss.backward()
        custom_optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 1, Loss: 0.3833
Epoch 2, Loss: 0.0678
Epoch 3, Loss: 0.0423


In [ ]:
## Evaluate 

In [ ]:
custom_torch_model.eval()  # disables dropout for evaluation
correct, total = 0, 0
with torch.no_grad():
    for images, labels in test_loader:
        outputs = custom_torch_model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"PyTorch Custom Model Test Accuracy: {correct / total * 100:.2f}%")